name: "тП▒я╕П Orchestrate EPG Pipeline (Bangladesh Time)"

on:
  schedule:
    # ржкрзНрж░рждрж┐ рзл ржорж┐ржирж┐ржЯ ржкрж░ ржкрж░ рж░рж╛ржи рж╣ржмрзЗ (UTC ржЕржирзБржпрж╛рзЯрзА, ржХрж┐ржирзНрждрзБ ржмрж╛ржВрж▓рж╛ржжрзЗрж╢рзЗржУ ржкрзНрж░рждрж┐ рзл ржорж┐ржирж┐ржЯ ржкрж░ржЗ рж╣ржмрзЗ)
    - cron: "*/5 * * * *"
  workflow_dispatch:           # ржорзНржпрж╛ржирзБржпрж╝рж╛рж▓рж┐ рж░рж╛ржи ржХрж░рж╛рж░ рж╕рзБржпрзЛржЧ
    inputs:
      reason:
        description: "ржорзНржпрж╛ржирзБржпрж╝рж╛рж▓рж┐ ржЪрж╛рж▓рж╛ржирзЛрж░ ржХрж╛рж░ржг (ржРржЪрзНржЫрж┐ржХ)"
        required: false
        default: "Manual trigger"

# ржЖрж▓рж╛ржжрж╛ concurrency group, ржпрзЗржи deadlock ржирж╛ рж╣рзЯ
concurrency:
  group: epg-orchestrator-${{ github.ref_name }}
  cancel-in-progress: false

permissions:
  contents: write

jobs:
  update_json_status:
    name: "1я╕ПтГг ЁЯЫ░я╕П JSON рж╕рзНржЯрзНржпрж╛ржЯрж╛рж╕ ржЖржкржбрзЗржЯ"
    uses: ./.github/workflows/update_json_status.yml
    secrets: inherit

  youtube_playlist:
    name: "2я╕ПтГг ЁЯОг YouTube ржкрзНрж▓рзЗрж▓рж┐рж╕рзНржЯ рждрзИрж░рж┐"
    needs: [update_json_status]
    uses: ./.github/workflows/youtube_playlist.yml
    secrets: inherit

  combine_playlists:
    name: "3я╕ПтГг ЁЯФА YouTube ржУ рж╕рзНржЯрзНржпрж╛ржЯрж┐ржХ IPTV рж▓рж┐ржВржХ ржПржХрждрзНрж░ ржХрж░рж╛"
    needs: [youtube_playlist]
    uses: ./.github/workflows/combine_playlists.yml
    secrets: inherit

  epg:
    name: "4я╕ПтГг ЁЯзнЁЯУ║ EPG ржЬрзЗржирж╛рж░рзЗржЯ ржУ ржкрзНрж░ржХрж╛рж╢ ржХрж░рж╛"
    needs: [combine_playlists]
    uses: ./.github/workflows/epg.yml
    secrets: inherit
